config/routes.rb
Rails.application.routes.draw do
  resources :events
  get 'home/index'

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  root 'home#index'

end

app/models/concerns/event_mixin.rb
module EventMixin
  extend ActiveSupport::Concern

  def start_time
    self.date
  end

  def view_class
    case self.tag
    when "red"
      "bg-danger"
    when "blue"
      "bg-info"
    when "yellow"
      "bg-warning"
    when "green"
      "bg-success"
    when "primary"
      "bg-primary"
    end
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  include EventMixin

  belongs_to :user
  has_many :repeats, dependent: :destroy
  accepts_nested_attributes_for :repeats

  # after_touch :remove_replicas
  after_save :replicate

  REPEAT = ["none", "daily", "weekly", "monthly", "yearly"]
  COLOR_TAG = ["primary", "red", "blue", "yellow", "green"]



  def replicate
    case self.repeat
    when "daily"
      # TODO: add :until field to the form
      all_dates = Recurrence.new(:starts => self.date,
                                 :every => :day,
                                 :until => '2017-12-31')
    when "weekly"
      all_dates = Recurrence.new(:starts => self.date,
                                 :every => :week,
                                 :on => Date.today.wday,
                                 :until => '2017-12-31')
    when "monthly"
      all_dates = Recurrence.new(:starts => self.date,
                                 :every => :month,
                                 :on => Date.today.mday,
                                 :until => '2017-12-31')
    when "yearly"
      all_dates = Recurrence.new(:starts => self.date,
                                 :every => :year,
                                 :on => Date.today.yday,
                                 :until => '2017-12-31')
    else
      all_dates = [Date.today]
    end

    all_dates.each do |date|
      event = Repeat.new(date: date,
                         event_id: self.id,
                         title: self.title,
                         tag: self.tag)
      event.save
    end
  end

end

app/models/repeat.rb
class Repeat < ActiveRecord::Base
  include EventMixin
  belongs_to :event

  scope :root_event, -> (id) { where(:event_id => id) }

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_current_events, only: [:update]
  # rescue_from ActiveRecord::RecordNotFound, with: :get_proper_record
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @personal_events = current_user.events.collect { |event| event.repeats }.flatten
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    if @event.user_id != current_user.id
      render(:file => File.join(Rails.root, 'public/422.html'), :status => 403, :layout => false)
    end
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update

    respond_to do |format|
      if @event.valid?
        @current_events.each { |entry| entry.delete }
      end
      if @event.update(event_params)
        format.html { redirect_to events_path, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }

      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :date, :repeat, :tag, :user_id)
    end

    # def get_proper_record
    #   @event = Event.find(Repeat.find(params[:id]).event_id)
    # end

    def set_current_events
      @current_events = Repeat.where event_id: @event.id
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events = Repeat.all
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_filter :configure_account_update_params, only: [:update]
  before_filter :configure_sign_up_params, only: [:create]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :fullname
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .field.form-group
    = f.label :title
    = f.text_field :title
  .field.form-group
    = f.label :tag
    = f.select :tag, options_for_select(Event::COLOR_TAG)
  .field.form-group
    = f.label :date
    = f.date_select :date
  .field.form-group
    = f.label :repeat
    = f.select :repeat, options_for_select(Event::REPEAT)
  .field.form-group



    - if user_signed_in?
      = f.hidden_field :user_id, value: current_user.id

  .actions
    = f.submit 'Сохранить', class: "btn btn-lg btn-primary"

app/views/events/edit.html.haml
%h2 Редактирование

= render 'form'

= link_to "Удалить", event_path, method: :delete, class: "btn btn-danger"

= link_to 'Назад', events_path, class: "btn btn-default"

app/views/events/index.html.haml
%h2 Личный календарь

= month_calendar events: @personal_events do |date, events|
  = date

  - events.each do |event|
    %div{class:"#{event.view_class}"}
      = link_to "#{event.title}", edit_event_path(event.event_id)

= link_to 'Новое событие', new_event_path, class: "btn btn-success"

app/views/events/new.html.haml
%h2 Новое событие

= render 'form'

= link_to 'Вернуться', events_path, class: "btn btn-default"

app/views/events/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @event.title
%p
  %b Date:
  = @event.date
%p
  %b Repeat:
  = @event.repeat

= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', events_path

app/views/home/index.html.haml
%h2 Calendar app with autorization
%p.text-muted Вы просматриваете общий для всех пользователей календарь

= month_calendar events: @events do |date, events|
  = date

  - events.each do |event|
    %div{class:"#{event.view_class}"}
      = event.title

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Календарь
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render "shared/flash_messages"
      .container

        %nav.navbar.navbar-default
          = render "shared/user_actions"

          = render "shared/menu"
    %main

      .container
        = yield

app/views/shared/_flash_messages.html.haml
- flash.each do |key, value|
  - if key == "alert"
    .bg-warning.flash
      .container
        = value
  - elsif key == "success"
    .bg-success.flash
      .container
        = value
  - elsif key == "error"
    .bg-danger.flash
      .container
        = value
  - elsif key == "notice"
    .bg-info.flash
      .container
        = value

app/views/shared/_menu.html.haml
- if current_user
  %ul.nav.navbar-nav
    %li
      = link_to 'Создать событие', new_event_path

app/views/shared/_user_actions.html.haml
- if current_user
  .dropdown
    .dropdown-toggle(data-toggle="dropdown")
      = current_user.email
      %span.caret
    %ul.dropdown-menu
      %li
        = link_to "Главная", root_path
      %li
        = link_to "Личный календарь", events_path unless current_page? events_path
      %li
        = link_to "Редактировать профиль", edit_user_registration_path
      %li
        = link_to "Выйти", destroy_user_session_path, method: :delete, class: "text-danger muted"

- else
  = link_to 'Войти', new_user_session_path, { :class=>"btn btn-default" }
  = link_to 'Регистрация', new_user_registration_path, { :class=>"btn btn-primary" }

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <%= link_to "Previous", calendar.url_for_previous_view %>
  <%= I18n.t("date.month_names")[start_date.month] %> <%= start_date.year %>
  <%= link_to "Next", calendar.url_for_next_view %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <%= link_to "Previous", calendar.url_for_previous_view %>
  <%= I18n.t("date.month_names")[start_date.month] %> <%= start_date.year %>
  <%= link_to "Next", calendar.url_for_next_view %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <%= link_to "Previous", calendar.url_for_previous_view %>
  Week <%= start_date.strftime("%U").to_i %>
  <%= link_to "Next", calendar.url_for_next_view %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>